Repository exadelsandbox2022feb/main, pull requests merged in 2022-03, with the labels that each got.

#84 Telegram bot greet with city and then office selection
  src/Api/Controllers/OfficeController.cs
  src/Api/Controllers/UserController.cs
  src/Api/DTO/PersonDto/SetUserDto.cs
  src/Api/Exadel.OfficeBooking.Api.csproj
  src/Api/Services/BookingService.cs
  src/Domain/Person/User.cs
  src/EF/DbTestData/OfficeTestData.cs
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/DTO/OfficeDto.cs
  src/TelegramApi/DTO/ServiceResponse.cs
  src/TelegramApi/EF/TelegramDbContext.cs
  src/TelegramApi/EF/UserState.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/FSM/FsmServicesExtension.cs
  src/TelegramApi/FSM/StateMachine.cs
  src/TelegramApi/FSM/Steps/ActionChoice.cs
  src/TelegramApi/FSM/Steps/Finish.cs
  src/TelegramApi/FSM/Steps/Greetings.cs
  src/TelegramApi/FSM/Steps/SelectBookingType.cs
  src/TelegramApi/FSM/Steps/SelectOffice.cs
  src/TelegramApi/FSM/Steps/Step.cs
  src/TelegramApi/Program.cs
  src/TelegramApi/TelegramBot.cs
Labels: size/xl

#97 Fix workplace creation
  src/Api/DTO/WorkplaceDto/WorkplaceSetDto.cs
  src/Domain/OfficePlan/Workplace.cs
  src/TelegramApi/TelegramBot.cs
Labels: size/s

#100 StateMachine fixed
  src/Api/Controllers/LoginController.cs
  src/Api/Controllers/OfficeController.cs
  src/Api/Controllers/UserController.cs
  src/Api/DTO/PersonDto/SetUserDto.cs
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/DTO/BookingTypeEnum.cs
  src/TelegramApi/DTO/OfficeDto.cs
  src/TelegramApi/DTO/OfficeDto/OfficeGetDto.cs
  src/TelegramApi/DTO/OfficeDto/OfficeSetDto.cs
  src/TelegramApi/DTO/PersonDto/LoginUserDto.cs
  src/TelegramApi/DTO/PersonDto/UserRole.cs
  src/TelegramApi/EF/TelegramDbContext.cs
  src/TelegramApi/EF/UserState.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/FSM/FsmServicesExtension.cs
  src/TelegramApi/FSM/StateMachine.cs
  src/TelegramApi/FSM/Steps/ActionChoice.cs
  src/TelegramApi/FSM/Steps/Finish.cs
  src/TelegramApi/FSM/Steps/Greetings.cs
  src/TelegramApi/FSM/Steps/SelectBookingType.cs
  src/TelegramApi/FSM/Steps/SelectOffice.cs
  src/TelegramApi/FSM/Steps/Step.cs
  src/TelegramApi/Program.cs
  src/TelegramApi/Properties/launchSettings.json
  src/TelegramApi/StateMachine/HttpResponse.cs
  src/TelegramApi/StateMachine/Result.cs
  src/TelegramApi/StateMachine/StateDb.cs
  src/TelegramApi/StateMachine/StateMachine.cs
  src/TelegramApi/StateMachine/StateMachineStep.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/StateMachine/WebApiHttpClientExtentions.cs
  src/TelegramApi/Steps/ActionChoice.cs
  src/TelegramApi/Steps/CityChoice.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/OfficeChoice.cs
  src/TelegramApi/Steps/ParkingChoice.cs
  src/TelegramApi/Steps/SpecParamChoice.cs
  src/TelegramApi/Steps/Start.cs
  src/TelegramApi/Steps/Template.cs
  src/TelegramApi/appsettings.json
Labels: size/xl

#102 Seed with real e-mail/telegram Id
  src/EF/DbTestData/ApplySeedData.cs
  src/EF/DbTestData/OfficeTestData.cs
  src/EF/DbTestData/UserTestData.cs
Labels: size/l

#108 Recurring booking step
  src/TelegramApi/DTO/RecurringFrequency.cs
  src/TelegramApi/DTO/WeekDays.cs
  src/TelegramApi/StateMachine/StateDb.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/DatesChoice.cs
Labels: size/l

#109 Parking implementation
  src/Api/Controllers/ParkingPlaceController.cs
  src/Api/DTO/ParkingPlaceDto/ParkingPlaceGetDto.cs
  src/Api/DTO/ParkingPlaceDto/ParkingPlaceSetDto.cs
  src/Api/Interfaces/IParkingPlaceService.cs
  src/Api/Program.cs
  src/Api/Properties/launchSettings.json
  src/Api/Services/ParkingPlaceService.cs
  src/EF/DbTestData/ApplySeedData.cs
  src/TelegramApi/DTO/ParkingPlaceDto/ParkingPlaceGetDto.cs
  src/TelegramApi/DTO/ParkingPlaceDto/ParkingPlaceSetDto.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/Program.cs
  src/TelegramApi/Steps/ParkingChoice.cs
  src/TelegramApi/Steps/ParkingPlaceSpecifications.cs
Labels: size/l

#111 Added step "ManageFor"
  src/Api/Controllers/LoginController.cs
  src/EF/DbTestData/ApplySeedData.cs
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/DTO/PersonDto/LoginUserDto.cs
  src/TelegramApi/Program.cs
  src/TelegramApi/StateMachine/Result.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/ManageForChoice.cs
  src/TelegramApi/Steps/Start.cs
  src/TelegramApi/TelegramBotClientExtensions.cs
Labels: size/l

#114 Send an email
  src/Api/Services/BookingService.cs
  src/Api/Services/EmailService.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
Labels: size/m

#105 Added PUT and DELETE request to HttpClientExtensions of WebAPI.
  src/Api/Properties/launchSettings.json
  src/TelegramApi/StateMachine/WebApiHttpClientExtentions.cs
Labels: size/m

#120 Closes #119
  src/TelegramApi/Steps/CityChoice.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/ManageForChoice.cs
  src/TelegramApi/Steps/OfficeChoice.cs
  src/TelegramApi/Steps/ParkingChoice.cs
  src/TelegramApi/Steps/SpecParamChoice.cs
  src/TelegramApi/Steps/Start.cs
Labels: size/m

#122 Fix first free workplace booking logic
  src/Api/Controllers/BookingController.cs
  src/Api/DTO/BookingDto/GetFirstFreeWorkplaceForBookingDto.cs
  src/Api/DTO/BookingDto/GetFirstFreeWorkplaceForRecuringBookingDto.cs
  src/Api/Exadel.OfficeBooking.Api.csproj
  src/Api/Interfaces/IBookingService.cs
  src/Api/Services/BookingService.cs
  src/EF/Exadel.OfficeBooking.EF.csproj
  src/TelegramApi/DTO/BookingDto/GetFirstFreeWorkplaceForBookingDto.cs
  src/TelegramApi/DTO/BookingDto/GetFirstFreeWorkplaceForRecuringBookingDto.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/Steps/SpecParamChoice.cs
Labels: size/l

#125 NewSeed
  src/EF/DbTestData/ApplySeedData.cs
Labels: size/m

#126 Step "WorkplaceChoice" added
  src/Api/Controllers/BookingController.cs
  src/Api/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/Api/Properties/launchSettings.json
  src/Api/Services/WorkplaceService.cs
  src/EF/DbTestData/ApplySeedData.cs
  src/TelegramApi/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/TelegramApi/Program.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/ConfirmBooking.cs
  src/TelegramApi/Steps/FloorChoice.cs
  src/TelegramApi/Steps/ManageForChoice.cs
  src/TelegramApi/Steps/SpecParamChoice.cs
  src/TelegramApi/Steps/WorkplaceChoice.cs
  src/TelegramApi/TelegramBotClientExtensions.cs
Labels: size/xl

#128 Parking place IsBooked now changes if booked
  src/Api/Controllers/ParkingPlaceController.cs
  src/Api/Properties/launchSettings.json
  src/Api/Services/ParkingPlaceService.cs
  src/TelegramApi/Steps/ParkingChoice.cs
Labels: size/s

#130 Updated WorkplaceFilterDto
  src/Api/Controllers/WorkplaceController.cs
  src/Api/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/Api/Interfaces/IWorkplaceService.cs
  src/Api/Services/WorkplaceService.cs
  src/TelegramApi/DTO/MapDto/MapFilterDto.cs
  src/TelegramApi/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/SpecParamChoice.cs
  src/TelegramApi/Steps/WorkplaceChoice.cs
  src/TelegramApi/TelegramBotClientExtensions.cs
Labels: size/l

#131 Confirm booking step
  src/TelegramApi/DTO/BookingDto/AddBookingDto.cs
  src/TelegramApi/DTO/BookingDto/AddRecurringBookingDto.cs
  src/TelegramApi/DTO/BookingDto/GetOneDayBookingDto.cs
  src/TelegramApi/DTO/BookingDto/GetRecurringBookingDto.cs
  src/TelegramApi/Steps/ConfirmBooking.cs
  src/TelegramApi/Steps/DatesChoice.cs
Labels: size/m

#134 Workplace filter method upgrade
  src/Api/Controllers/WorkplaceController.cs
  src/Api/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/Api/Interfaces/IBookingService.cs
  src/Api/Interfaces/IWorkplaceService.cs
  src/Api/Services/BookingService.cs
  src/Api/Services/WorkplaceService.cs
  src/TelegramApi/DTO/WorkplaceDto/WorkplaceFilterDto.cs
Labels: size/l

#136 Send E-mail with info to user
  src/Api/Services/BookingService.cs
Labels: size/xs

#140 Calendar added to the "DatesChoice" step
  src/Api/DTO/BookingDto/RecurrencePattern.cs
  src/TelegramApi/Calendar/Constants.cs
  src/TelegramApi/Calendar/Markup.cs
  src/TelegramApi/Calendar/Row.cs
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/DTO/BookingDto/RecurrencePattern.cs
  src/TelegramApi/DTO/BookingDto/WeekDays.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/ConfirmBooking.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/SpecParamChoice.cs
  src/TelegramApi/StringHtmlExtensions.cs
  src/TelegramApi/TelegramBotClientExtensions.cs
Labels: size/xl

#142 Parsing format for date time
  src/TelegramApi/Steps/DatesChoice.cs
Labels: size/xs

#148 Select user so Admin can book for them, exclude other admins
  src/TelegramApi/Steps/ManageForChoice.cs
Labels: size/xs

#150 Added booking selection logic into ActionChoice
  src/Api/Properties/launchSettings.json
  src/Api/Services/BookingService.cs
  src/TelegramApi/DTO/BookView.cs
  src/TelegramApi/Program.cs
  src/TelegramApi/StateMachine/StateDb.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/ActionChoice.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/EditingChoise.cs
  src/TelegramApi/Steps/ManageForChoice.cs
  src/TelegramApi/Steps/Start.cs
  src/TelegramApi/TelegramBotClientExtensions.cs
  src/TelegramApi/Tgm/InlineKbMarkups.cs
Labels: size/xl

#152 Report flow
  src/TelegramApi/DTO/ReportDto/DailyReportDto.cs
  src/TelegramApi/DTO/ReportDto/OfficeReportDto.cs
  src/TelegramApi/Program.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/OfficeChoice.cs
  src/TelegramApi/Steps/OfficeReportChoice.cs
  src/TelegramApi/Steps/Start.cs
Labels: size/m

#154 Fix report flow
  src/Api/Controllers/ReportController.cs
  src/TelegramApi/Calendar/Markup.cs
  src/TelegramApi/StateMachine/UserState.cs
  src/TelegramApi/Steps/DatesChoice.cs
  src/TelegramApi/Steps/OfficeChoice.cs
  src/TelegramApi/Steps/OfficeReportChoice.cs
  src/TelegramApi/Steps/Start.cs
  src/TelegramApi/TelegramBotClientExtensions.cs
Labels: size/l

#157 Added email configuration in appsettings
  src/Api/Interfaces/IEmailService.cs
  src/Api/Program.cs
  src/Api/Services/BookingService.cs
  src/Api/Services/EmailService.cs
Labels: size/s
