Repository exadelsandbox2022feb/main, pull requests merged in 2022-02, with the labels that each got.

#29 Notifications model #23
  src/Domain/Notifications/AutoCancellationNotification.cs
  src/Domain/Notifications/BookingNotification.cs
Labels: enhancement, help wanted, question

#39 Add booking model and change API project
  src/Api/Controllers/WeatherForecastController.cs
  src/Api/Program.cs
  src/Api/Properties/launchSettings.json
  src/Api/WeatherForecast.cs
  src/Domain/Bookings/Booking.cs
  src/Domain/Bookings/RecuringBooking.cs
  src/Domain/OfficePlan/Office.cs
  src/Domain/OfficePlan/ParkingPlace.cs
  src/Domain/OfficePlan/Workplace.cs
  src/Domain/Person/User.cs
  src/Domain/Person/Vacation.cs
  src/Exadel.OfficeBooking.sln
Labels: size/l

#43 Correction AppDbContext and switch to MSSql
  src/Api/DB/OfficeBooking.db
  src/Api/Exadel.OfficeBooking.Api.csproj
  src/Api/Program.cs
  src/Api/appsettings.json
  src/Domain/Bookings/Booking.cs
  src/Domain/OfficePlan/ParkingPlace.cs
  src/EF/AppDbContext.cs
  src/EF/Exadel.OfficeBooking.EF.csproj
  src/EF/Migrations/20220206074357_InitialCreate.Designer.cs
  src/EF/Migrations/20220206074357_InitialCreate.cs
  src/EF/Migrations/AppDbContextModelSnapshot.cs
Labels: size/xl

#45 Gitignore and small fixes
  .gitignore
  src/Api/Program.cs
  src/Api/appsettings.json
  src/Domain/Bookings/Booking.cs
  src/Domain/Notifications/BookingNotification.cs
  src/Domain/OfficePlan/ParkingPlace.cs
  src/Domain/OfficePlan/Workplace.cs
  src/Domain/Person/User.cs
  src/EF/AppDbContext.cs
Labels: size/l

#48 Created ServiceResponse model
  src/Api/DTO/ServiceResponse.cs
Labels: size/xs

#46 Office endpoints
  .gitignore
  src/Api/Controllers/OfficesController.cs
  src/Api/Controllers/UsersController.cs
  src/Api/DTO/OfficeDto.cs
  src/Api/DTO/OfficeFilterDto.cs
  src/Api/Exadel.OfficeBooking.Api.csproj
  src/Api/Interfaces/IOfficeService.cs
  src/Api/Program.cs
  src/Api/Services/OfficeService.cs
  src/Domain/BaseModel.cs
  src/Domain/Bookings/Booking.cs
  src/Domain/Bookings/RecuringBooking.cs
  src/Domain/Exadel.OfficeBooking.Domain.csproj
  src/Domain/Notifications/BookingNotification.cs
  src/Domain/OfficePlan/Map.cs
  src/Domain/OfficePlan/Office.cs
  src/Domain/OfficePlan/Workplace.cs
  src/Domain/Person/User.cs
  src/Domain/Person/Vacation.cs
  src/Domain/Reports/AllOfficesReport.cs
  src/Domain/Reports/CityReport.cs
  src/Domain/Reports/DailyReport.cs
  src/Domain/Reports/EmployeeDailyReport.cs
  src/Domain/Reports/EmployeeReport.cs
  src/Domain/Reports/FloorReport.cs
  src/Domain/Reports/OfficeReport.cs
  src/EF/AppDbContext.cs
  src/EF/Exadel.OfficeBooking.EF.csproj
Labels: size/l

#49 Workplace endpoins
  .gitignore
  src/Api/Controllers/OfficesController.cs
  src/Api/Controllers/WorkplaceController.cs
  src/Api/DTO/OfficeDto.cs
  src/Api/DTO/OfficeDto/OfficeFilterDto.cs
  src/Api/DTO/OfficeDto/OfficeGetDto.cs
  src/Api/DTO/OfficeDto/OfficeSetDto.cs
  src/Api/DTO/ServiceResponse.cs
  src/Api/DTO/WorkplaceDto/TypesDto.cs
  src/Api/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/Api/DTO/WorkplaceDto/WorkplaceGetDto.cs
  src/Api/DTO/WorkplaceDto/WorkplaceSetDto.cs
  src/Api/Interfaces/IOfficeService.cs
  src/Api/Interfaces/IWorkplaceService.cs
  src/Api/Program.cs
  src/Api/Services/OfficeService.cs
  src/Api/Services/WorkplaceService.cs
  src/Domain/OfficePlan/Workplace.cs
Labels: size/xl

#54 Vacation and User endpoints
  src/Api/Controllers/UserController.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Controllers/VacationController.cs
  src/Api/DTO/UserDto.cs
  src/Api/DTO/VacationDto.cs
  src/Domain/Person/User.cs
Labels: size/l

#55 #51 Initial Telegram project.
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/Program.cs
  src/TelegramApi/Properties/launchSettings.json
  src/TelegramApi/TelegramModel.cs
  src/TelegramApi/appsettings.Development.json
  src/TelegramApi/appsettings.json
Labels: size/m

#57 Telegram api deployment
  .github/workflows/telegram-api-deploy.yml
Labels: size/s

#60 Fixed Office endpoint
  src/Api/Controllers/OfficeController.cs
  src/Api/DTO/OfficeDto/OfficeFilterDto.cs
  src/Api/DTO/OfficeDto/OfficeSetDto.cs
  src/Api/Interfaces/IOfficeService.cs
  src/Api/Services/OfficeService.cs
  src/Domain/OfficePlan/Office.cs
  src/EF/AppDbContext.cs
Labels: size/m

#64 Make telegram api startable
  src/Api/Program.cs
  src/Exadel.OfficeBooking.sln
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/Program.cs
  src/TelegramApi/TelegramModel.cs
  src/TelegramApi/appsettings.json
Labels: size/s

#68 Db test population
  src/EF/AppDbContext.cs
  src/EF/DbTestData/OfficeTestData.cs
  src/EF/DbTestData/UserTestData.cs
  src/EF/Exadel.OfficeBooking.EF.csproj
Labels: size/m

#65 Booking endpoints
  src/Api/Controllers/BookingController.cs
  src/Api/DTO/BookingDto/AddBookingDto.cs
  src/Api/DTO/BookingDto/AddRecurringBookingDto.cs
  src/Api/DTO/BookingDto/GetBookingDto.cs
  src/Api/DTO/BookingDto/GetOneDayBookingDto.cs
  src/Api/DTO/BookingDto/GetRecurringBookingDto.cs
  src/Api/DTO/BookingDto/RecurrencePattern.cs
  src/Api/DTO/BookingDto/UpdateBookingDto.cs
  src/Api/DTO/BookingDto/UpdateRecurringBookingDto.cs
  src/Api/DTO/ServiceResponse.cs
  src/Api/Interfaces/IBookingService.cs
  src/Api/Program.cs
  src/Api/Services/BookingService.cs
  src/Domain/Bookings/Booking.cs
  src/Domain/Bookings/RecuringBooking.cs
  src/Domain/Bookings/RecurringFrequency.cs
  src/Domain/Person/User.cs
Labels: size/xl

#58 #52
  src/Exadel.OfficeBooking.sln
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/Program.cs
  src/TelegramApi/TelegramBot.cs
  src/TelegramApi/TelegramModel.cs
  src/TelegramApi/appsettings.json
Labels: size/m

#72 Trying to fix the bot
  src/Api/Controllers/OfficeController.cs
  src/TelegramApi/Controllers/TelegramApiController.cs
  src/TelegramApi/Exadel.OfficeBooking.TelegramApi.csproj
  src/TelegramApi/Program.cs
  src/TelegramApi/Properties/launchSettings.json
  src/TelegramApi/TelegramBot.cs
Labels: size/m

#75 Added map endpoint as it required in BA requirements - issue #32
  src/Api/Controllers/MapController.cs
  src/Api/DTO/MapDto.cs
  src/Api/Interfaces/IMapService.cs
  src/Api/Program.cs
  src/Api/Services/MapService.cs
Labels: size/l

#77 Workplaceсontroller optimization
  .gitignore
  src/Api/Controllers/MapController.cs
  src/Api/Controllers/OfficeController.cs
  src/Api/Controllers/WorkplaceController.cs
  src/Api/DTO/MapDto.cs
  src/Api/DTO/MapDto/MapGetDto.cs
  src/Api/DTO/MapDto/MapSetDto.cs
  src/Api/DTO/WorkplaceDto/WorkplaceFilterDto.cs
  src/Api/DTO/WorkplaceDto/WorkplaceSetDto.cs
  src/Api/DTO/WorkplaceDto/WorkplaceTypesDto.cs
  src/Api/Interfaces/IMapService.cs
  src/Api/Interfaces/IOfficeService.cs
  src/Api/Interfaces/IWorkplaceService.cs
  src/Api/Program.cs
  src/Api/Services/MapService.cs
  src/Api/Services/OfficeService.cs
  src/Api/Services/WorkplaceService.cs
  src/Domain/OfficePlan/Map.cs
  src/Domain/OfficePlan/Workplace.cs
  src/EF/AppDbContext.cs
  src/EF/DbTestData/UserTestData.cs
  src/EF/Exadel.OfficeBooking.EF.csproj
  src/TelegramApi/Program.cs
Labels: size/l

#79 Enum flags for booking
  src/Api/DTO/BookingDto/AddBookingDto.cs
  src/Api/DTO/BookingDto/AddRecurringBookingDto.cs
  src/Api/DTO/BookingDto/GetBookingDto.cs
  src/Api/DTO/BookingDto/GetOneDayBookingDto.cs
  src/Api/DTO/BookingDto/GetRecurringBookingDto.cs
  src/Api/DTO/BookingDto/RecurrencePattern.cs
  src/Api/DTO/BookingDto/UpdateBookingDto.cs
  src/Api/DTO/BookingDto/UpdateRecurringBookingDto.cs
  src/Api/Services/BookingService.cs
  src/Domain/Bookings/Booking.cs
  src/Domain/Bookings/WeekDays.cs
Labels: size/m

#83 Fixed Person model
  src/Api/Controllers/LoginController.cs
  src/Api/Controllers/UserController.cs
  src/Api/Controllers/VacationController.cs
  src/Api/DTO/PersonDto/GetUserDto.cs
  src/Api/DTO/PersonDto/GetVacationDto.cs
  src/Api/DTO/PersonDto/LoginUserDto.cs
  src/Api/DTO/PersonDto/SetUserDto.cs
  src/Api/DTO/PersonDto/SetVacationDto.cs
  src/Api/DTO/VacationDto.cs
Labels: size/l

#86 Seed TestOffice with Map, Parkingplace, Workplace
  src/Api/DTO/ServiceResponse.cs
  src/Api/Interfaces/IBookingService.cs
  src/Domain/OfficePlan/Map.cs
  src/Domain/OfficePlan/ParkingPlace.cs
  src/Domain/OfficePlan/Workplace.cs
  src/EF/AppDbContext.cs
  src/EF/DbTestData/ApplySeedData.cs
  src/EF/DbTestData/OfficeTestData.cs
Labels: size/l
